### ISSUE TITLE
[feat] 쿠폰 API

### ISSUE THREAD

**Issue by cod2048** [neul-poom/backend#4]
- 쿠폰 기능

## TODO
- [x] 컨트롤러 작성
- [x] 서비스 로직 구현
    - [x] 쿠폰 등록
    - [x] 쿠폰 조회 (단일 쿠폰 조회, 전체 쿠폰 조회)
    - [x] 쿠폰 수정
    - [x] 쿠폰 삭제
    - [x] 쿠폰 상태 변경
    - [x] 상태 별 쿠폰 조회 (유효한 쿠폰 목록 조회, 만료된 쿠폰 목록 조회)
